name: zMushroom
version: '1.4-Beta'
author: zPleum
description: © 2025 zPleum. Licensed under MIT License.
website: https://zpleum.site/
main: me.zpleum.zMushroom.ZMushroom
api-version: '1.21'

commands:
  zmushroom:
    description: Reloads the plugin configuration and cooldowns.
    usage: /zmushroom reload
    permission: zmushroom.reload
    permission-message: You do not have permission to use this command.
permissions:
  zmushroom.reload:
    description: Allows the player to reload the plugin configuration.
    default: op
